# Generated by Django 3.2.18 on 2023-06-15 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productImageUrl', models.CharField(max_length=10000)),
                ('productName', models.CharField(max_length=50)),
                ('productPrice', models.IntegerField()),
                ('productId', models.IntegerField(primary_key=True, serialize=False)),
                ('productTag', models.CharField(max_length=30)),
                ('productDescription', models.CharField(max_length=10000)),
                ('productRating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField()),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField()),
                ('productId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
            ],
        ),
    ]
