# Generated by Django 3.2.18 on 2023-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_product_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(max_length=10000),
        ),
    ]
